// apps/admin/components/DemoModeBanner.tsx
import React from 'react';

export function DemoModeBanner(): React.ReactElement {
  return (
    <div className="bg-amber-50 dark:bg-amber-950/30 border-b border-amber-200 dark:border-amber-900/50 px-4 py-2 flex items-center justify-center gap-2 text-sm text-amber-800 dark:text-amber-300">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/>
        <line x1="12" y1="9" x2="12" y2="13"/>
        <line x1="12" y1="17" x2="12.01" y2="17"/>
      </svg>
      <span className="font-medium">Portfolio demo — seeded supply-chain verification scenario</span>
    </div>
  );
}

// apps/consumer/src/domains/layout/DemoModeBanner.vue
<script setup lang="ts">
import { UI_CONSTANTS } from '@/lib/demo/demoScenario';
</script>

<template>
  <div class="w-full py-2 px-4 flex items-center justify-center border-b border-[var(--color-bp-outline-ghost)] bg-bp-error-container">
    <div class="flex items-center gap-2">
      <svg class="w-4 h-4 text-bp-error" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span class="bp-mono text-xs font-bold uppercase tracking-widest text-bp-on-error-container text-center">
        {{ UI_CONSTANTS.BANNER_TEXT }}
      </span>
    </div>
  </div>
</template>

<style scoped>
.bp-mono {
  font-family: var(--font-bp-mono);
}
</style>
